# Generated by Django 2.2.12 on 2020-04-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='NewsStory',
        ),
    ]
